title: cvless
description: Jekyll theme for a beautiful online CV
baseurl: ""
url: https://www.ionstat.uk/

#theme: cvless
remote_theme: piazzai/cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme

# author settings
author:
  name: ionstat
  email: hello@ionstat.com
photo: assets/files/photo.png
address: Earth
phone: +1 234 567 890

# profile links
profile:
  facebook: https://www.facebook.com/username
  x: https://x.com/username
  mastodon: https://mastodon.social/@username
  bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/username
  xing: https://www.xing.com/profile/username
  stackoverflow: https://stackoverflow.com/users/0000000/username
  medium: https://medium.com/@username
  github: https://github.com/username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
