title: Mathew West
description: Experienced IT Professional | Hardware | Software | Development | ERP
baseurl: ""
url: https://www.ionstat.uk/

#theme: cvless
remote_theme: piazzai/cvless

# site settings
taglong: Experienced IT Professional | Hardware | Software | Development | ERP
tagshort: Mathew West

# author settings
author:
  name: Mathew West
  email: hello@ionstat.uk
photo: assets/files/photo.png
address: Earth
phone: +44 300 180 0602

# profile links
profile:
  facebook: https://www.facebook.com/matwest92
  mastodon: https://mastodon.social/@matwest92
  bluesky: https://bsky.app/profile/w3s7.net
  instagram: https://www.instagram.com/matwest92
  linkedin: https://www.linkedin.com/in/mathewwest
  github: https://github.com/ionstat

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
